#!python
# -*- coding: utf-8 -*-
import re
import sys

if __name__ == '__main__':
    # sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    # sys.exit(main())
    print("hey there")
    sys.exit(1)
